"""Chat tables: threads, messages, llm_calls.

Written as plain SQL on purpose: this is the DDL you review, exactly as it runs.
tests/test_db.py checks it matches kirana_ai/db/models.py.

Revision ID: 0001
Revises:
"""
from alembic import op

revision = "0001"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    op.execute("""
        CREATE TABLE ai.threads (
            id          UUID         NOT NULL,
            user_id     BIGINT       NOT NULL,   -- a Kirana user id; no FK across services
            title       VARCHAR(200) NOT NULL,
            created_at  TIMESTAMPTZ  NOT NULL DEFAULT now(),
            updated_at  TIMESTAMPTZ  NOT NULL DEFAULT now(),
            CONSTRAINT pk_threads PRIMARY KEY (id)
        );
        CREATE INDEX ix_threads_user_id_updated_at ON ai.threads (user_id, updated_at DESC);

        CREATE TABLE ai.messages (
            id          UUID         NOT NULL,
            thread_id   UUID         NOT NULL,
            role        VARCHAR(20)  NOT NULL,
            content     TEXT         NOT NULL,
            citations   JSONB        NOT NULL DEFAULT '[]',
            tool_steps  JSONB        NOT NULL DEFAULT '[]',
            created_at  TIMESTAMPTZ  NOT NULL DEFAULT now(),
            CONSTRAINT pk_messages PRIMARY KEY (id),
            CONSTRAINT fk_messages_thread_id_threads FOREIGN KEY (thread_id)
                REFERENCES ai.threads (id) ON DELETE CASCADE,
            CONSTRAINT ck_messages_role CHECK (role IN ('user', 'assistant'))
        );
        CREATE INDEX ix_messages_thread_id_created_at ON ai.messages (thread_id, created_at);

        CREATE TABLE ai.llm_calls (
            id             BIGINT GENERATED BY DEFAULT AS IDENTITY,
            thread_id      UUID,          -- no FKs: cost rows must outlive failed turns
            turn_id        UUID,
            provider       VARCHAR(30)    NOT NULL,
            model          VARCHAR(100)   NOT NULL,
            status         VARCHAR(20)    NOT NULL,
            input_tokens   INTEGER,
            output_tokens  INTEGER,
            latency_ms     INTEGER        NOT NULL,
            cost_usd       NUMERIC(12, 6),  -- NULL = model not in pricing.yaml, not free
            error          TEXT,
            created_at     TIMESTAMPTZ    NOT NULL DEFAULT now(),
            CONSTRAINT pk_llm_calls PRIMARY KEY (id),
            CONSTRAINT ck_llm_calls_status CHECK (status IN ('ok', 'error'))
        );
        CREATE INDEX ix_llm_calls_turn_id ON ai.llm_calls (turn_id);
        CREATE INDEX ix_llm_calls_created_at ON ai.llm_calls (created_at);
    """)


def downgrade() -> None:
    op.execute("DROP TABLE ai.llm_calls; DROP TABLE ai.messages; DROP TABLE ai.threads;")
