"""Phase 6 M1: the tool policy layer's decision log.

Revision ID: 0003
Revises: 0002
"""
from alembic import op

revision = "0003"
down_revision = "0002"
branch_labels = None
depends_on = None


def upgrade() -> None:
    op.execute("""
        CREATE TABLE ai.tool_decisions (
            id          BIGINT GENERATED BY DEFAULT AS IDENTITY,
            thread_id   UUID,
            turn_id     UUID,
            user_id     BIGINT,
            tool        VARCHAR(60)   NOT NULL,             -- as the model named it, even if unknown
            arguments   JSONB         NOT NULL DEFAULT '{}',
            args_hash   VARCHAR(16)   NOT NULL,
            decision    VARCHAR(20)   NOT NULL,
            reason      VARCHAR(200)  NOT NULL,             -- e.g. missing-scope:orders:read, unknown-tool
            layer       VARCHAR(20)   NOT NULL,             -- who decided: policy, or kirana (its 403/404)
            created_at  TIMESTAMPTZ   NOT NULL DEFAULT now(),
            CONSTRAINT pk_tool_decisions PRIMARY KEY (id),
            CONSTRAINT ck_tool_decisions_decision CHECK (decision IN ('allow', 'deny', 'approval')),
            CONSTRAINT ck_tool_decisions_layer CHECK (layer IN ('policy', 'kirana'))
        );
        CREATE INDEX ix_tool_decisions_turn_id ON ai.tool_decisions (turn_id);
        CREATE INDEX ix_tool_decisions_user_id_created_at ON ai.tool_decisions (user_id, created_at);
    """)


def downgrade() -> None:
    op.execute("DROP TABLE ai.tool_decisions;")
